export const THEMES: string[] = [
  'Aliens',
  'Cowboys',
  'Indians',
  'Middle-ages',
  'Ancient Egypt',
  'Cyberpunk',
  'Post-apocalyptic',
  'Dinosaurs',
  'Underwater',
  'Ghosts',
  'Monsters',
  'Roman Empire',
  'Greek Gods',
  'Mythical',
  'Religious',
  'Renaissance/Golden Age',
  'Steampunk',
  'Robots',
  'Fifties',
  'Modern Day',
  'Futuristic',
  'Noir',
  'Fantasy',
  'Space',
  'Jobs',
  'Nordic/Vikings',
  'Ice Age',
  'Nomads/Tribes',
  'Jungle',
  'Gothics/Castle',
  'Pirates',
];
