export const TOPICS: string[] = [
  'Time Travel',
  'Uprising/Rebellion',
  'Survival',
  'Plague',
  'Horror/Scary',
  'Apocalyptic',
  'Business Empire',
  'Love',
  'Manipulation',
  'Evil',
  'Detective',
  'Espionage',
  'Shape Shifters',
  'Trapped/Escape',
  'Political Empires',
  'Weird Towns/Intrigue',
  'Battle',
  'Exploration',
  'Colonies/VOC',
  'City/Town',
  'Vehicles/Transportation',
  'Character Transformation',
  'Transformation/Evolution',
  'Sacrifice',
  'Illusion/Magic',
  'Betrayal',
  'Redemption',
  'Legacy',
  'Competition/Rivalry',
];
